export const project = [
  {
    url: 'https://nooors.github.io/pipesApp/',
    code: 'https://github.com/nooors/pipesApp.git',
    description: '',
    tech: [
      'Angular 14',
      'router 14',
      'lazy-loading',
      'primeNg 14',
      'primeFlex 3',
      'RxJS 7',
    ],
    thumbnail: '',
  },
  {
    url: 'https://nooors.github.io/HeroesApp/auth/login',
    code: [
      { frontend: 'https://github.com/nooors/HeroesApp.git' },
      { backend: 'https://github.com/nooors/heroesDB.git' },
    ],
    description: '',
    tech: [
      'Angular 13',
      'flex-layout 13',
      'angular-material 13',
      'router 13',
      'lazy-loading',
      'Protected routes',
      'RxJS 7',
      'HttpClient',
      'Json-server, API',
    ],
    thumbnail: '',
  },
  {
    url: 'https://nooors.github.io/countriesApp/',
    code: 'https://github.com/nooors/countriesApp.git',
    description: '',
    tech: [
      'Angular 13',
      'Forms',
      'Router 13',
      'Bootstrap 5',
      'RxJS 7',
      'HttpClient',
      'API',
    ],
    thumbnail: '',
  },
  {
    url: 'https://nooors.github.io/weather-angular-app/',
    code: 'https://github.com/nooors/weather-angular-app.git',
    description: '',
    tech: [
      'Angular 13',
      'Reactive-Forms',
      'Router 13',
      'RxJS',
      'Interceptors',
      'HttpClient',
      'API',
    ],
    thumbnail: '',
  },
  {
    url: 'https://nooors.github.io/router-tour-of-heroes/',
    code: 'https://github.com/nooors/router-tour-of-heroes.git',
    description: '',
    tech: ['Angular 13', 'Router 13', 'Protected routes', 'RxJS'],
  },
  {
    url: 'https://angular-node-back-front-auth.herokuapp.com/auth/login',
    code: [
      { backend: 'https://github.com/nooors/auth-serve-node.git' },
      { frontend: 'https://github.com/nooors/auth-app.git' },
    ],
    description: '',
    tech: [
      'Angular 13',
      'Router 13',
      'Reactive Forms',
      'RxJS',
      'HttpClient',
      'SweetAlert 2',
      'NodeJS',
      'Express 4',
      'Mongo DB',
      'BccryptJS',
      'JWT',
    ],
    thumbnail: '',
  },
  {
    url: 'https://nooors.github.io/todo-trainee/',
    code: 'https://github.com/nooors/todo-trainee.git',
    description: '',
    tech: [
      'Angular 13',
      'Angular Material 13',
      'Router 13',
      'Reactive Forms',
      'Dymanic Forms',
      'RxJS',
      'HttpClient',
      'Json-server',
      'API',
      'PosgreSQL',
    ],
    thumbnail: '',
  },
];
